CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    SECOND_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DELETED BOOLEAN NOT NULL DEFAULT FALSE
);