CREATE TABLE IF NOT EXISTS ITEMS (
  ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PRICE DOUBLE NOT NULL,
  QUANITY INTEGER,
  SHORT_DESCRIPTION VARCHAR(255),
  FULL_DESCRIPTION VARCHAR(255),
  DELETED BOOLEAN NOT NULL DEFAULT FALSE
);