CREATE TABLE IF NOT EXISTS ITEMS (
  ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PRICE DOUBLE NOT NULL,
  QUANTITY INTEGER,
  SHORT_DESCRIPTION VARCHAR(255),
  FULL_DESCRIPTION VARCHAR(255),
  DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  CATEGORY_ID LONG NOT NULL,
  CONSTRAINT FK_ITEM_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(ID)
);