INSERT INTO ITEMS(NAME, PRICE) VALUES ('deskorolka', 250);
INSERT INTO ITEMS(NAME, PRICE) VALUES ('hulajnoga', 120);
INSERT INTO ITEMS(NAME, PRICE) VALUES ('stół', 100);
INSERT INTO ITEMS(NAME, PRICE) VALUES ('krzesło', 50);