CREATE TABLE IF NOT EXISTS ORDERS (
    ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SUMMARY DOUBLE NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
);

ALTER TABLE ITEMS ADD ORDER_ID LONG;
ALTER TABLE PUBLIC.ITEMS ADD FOREIGN KEY(ORDER_ID) REFERENCES PUBLIC.ORDERS(ID);
