CREATE TABLE IF NOT EXISTS ORDERS (
    ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SUMMARY DOUBLE NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    USER_ID VARCHAR(255)
);

ALTER TABLE ITEMS ADD ORDER_ID LONG;
ALTER TABLE PUBLIC.ITEMS ADD FOREIGN KEY(ORDER_ID) REFERENCES PUBLIC.ORDERS(ID);
ALTER TABLE PUBLIC.ORDERS ADD FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USERS(USERNAME);

