CREATE TABLE IF NOT EXISTS ORDERITEMS (
  ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  PRICE DOUBLE NOT NULL,
  QUANITY LONG NOT NULL,
  SHORT_DESCRIPTION VARCHAR(255) NOT NULL,
  FULL_DESCRIPTION VARCHAR(255) NOT NULL,
  DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  CATEGORY_ID LONG NOT NULL,
  ORDER_ID LONG NOT NULL,
  CONSTRAINT FK_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(ID),
  CONSTRAINT FK_ORDER FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID)
);

DROP TABLE CUSTOMER;

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED, NAME, LASTNAME, EMAIL, ZIPCODE, ADDRESS, CITY ) VALUES ('admin', 'admin', TRUE,'administrator','adminek', 'admin@domain.com',42900, 'ADDRESS', 'CITY');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('admin', 'ADMIN');
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED, NAME, LASTNAME, EMAIL, ZIPCODE, ADDRESS, CITY ) VALUES ('mod', 'mod', TRUE,'mod','mod', 'mod@domain.com',42900, 'ADDRESS', 'CITY');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('mod', 'MODERATOR');
INSERT INTO USERS(USERNAME, PASSWORD, ENABLED, NAME, LASTNAME, EMAIL, ZIPCODE, ADDRESS, CITY ) VALUES ('user', 'user', TRUE,'user','user', 'user@domain.com',42900, 'ADDRESS', 'CITY');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ('user', 'USER');
