CREATE TABLE IF NOT EXISTS CITY (
    ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CITY VARCHAR(255),
    ZIPCODE VARCHAR(255)
);

INSERT INTO CITY(ZIPCODE, CITY) VALUES ('00-001', 'Warszawa');
INSERT INTO CITY(ZIPCODE, CITY) VALUES ('12-345', 'Kraków');
INSERT INTO CITY(ZIPCODE, CITY) VALUES ('41-908', 'Bytom');
INSERT INTO CITY(ZIPCODE, CITY) VALUES ('22-222', 'Katowice');
INSERT INTO CITY(ZIPCODE, CITY) VALUES ('33-333', 'Bydgoszcz');